/**
 * Generates src/icons.generated.ts from @iconify-json/solar (CC BY 4.0, 480 Design).
 * Add a name to WANTED and run `bun scripts/generate-icons.ts`.
 */
import icons from '@iconify-json/solar/icons.json' with { type: 'json' };

const WANTED: Record<string, string> = {
  sessions: 'chat-round-dots-bold',
  sessionsLine: 'chat-round-dots-linear',
  add: 'add-circle-bold',
  addLine: 'add-circle-linear',
  plus: 'add-square-bold',
  settings: 'settings-bold',
  settingsLine: 'settings-linear',
  back: 'alt-arrow-left-linear',
  chevronRight: 'alt-arrow-right-linear',
  chevronDown: 'alt-arrow-down-linear',
  chevronUp: 'alt-arrow-up-linear',
  send: 'plain-bold',
  arrowUp: 'arrow-up-bold',
  stop: 'stop-bold',
  folder: 'folder-bold',
  folderOpen: 'folder-open-bold',
  folderCode: 'folder-with-files-bold',
  search: 'magnifer-linear',
  terminal: 'code-square-bold',
  code: 'code-bold',
  file: 'document-text-bold',
  edit: 'pen-bold',
  rename: 'pen-new-square-bold',
  newChat: 'pen-new-square-linear',
  globe: 'global-bold',
  checklist: 'checklist-minimalistic-bold',
  shieldCheck: 'shield-check-bold',
  shieldWarning: 'shield-warning-bold',
  check: 'check-circle-bold',
  checkLine: 'check-read-linear',
  close: 'close-circle-bold',
  closeLine: 'close-square-linear',
  danger: 'danger-triangle-bold',
  more: 'menu-dots-bold',
  archive: 'archive-bold',
  trash: 'trash-bin-trash-bold',
  phone: 'smartphone-bold',
  laptop: 'laptop-bold',
  monitor: 'monitor-bold',
  language: 'translation-bold',
  sun: 'sun-bold',
  moon: 'moon-bold',
  palette: 'pallete-2-bold',
  bulb: 'lightbulb-minimalistic-bold',
  link: 'link-round-bold',
  qr: 'qr-code-bold',
  copy: 'copy-bold',
  info: 'info-circle-bold',
  refresh: 'refresh-bold',
  cpu: 'cpu-bolt-bold',
  bolt: 'bolt-bold',
  lock: 'lock-keyhole-bold',
  wifi: 'wi-fi-router-bold',
  logout: 'logout-2-bold',
  task: 'clipboard-list-bold',
  robot: 'cpu-bold',
  play: 'play-bold',
  history: 'history-bold',
  home: 'home-2-bold',
  image: 'gallery-bold',
  user: 'user-rounded-bold',
};

const all = icons as {
  icons: Record<string, { body: string; width?: number; height?: number }>;
  aliases?: Record<string, { parent: string }>;
  width?: number;
  height?: number;
};
const resolve = (name: string) => all.icons[name] ?? (all.aliases?.[name] ? all.icons[all.aliases[name]!.parent] : undefined);
const out: Record<string, { body: string; width: number; height: number }> = {};
const missing: string[] = [];
for (const [alias, name] of Object.entries(WANTED)) {
  const icon = resolve(name);
  if (!icon) {
    missing.push(name);
    continue;
  }
  out[alias] = { body: icon.body, width: icon.width ?? all.width ?? 24, height: icon.height ?? all.height ?? 24 };
}
if (missing.length) {
  console.error('missing Solar icons:', missing.join(', '));
  process.exit(1);
}
const file = `/*
 * GENERATED by scripts/generate-icons.ts. Do not edit by hand.
 * Source: Solar icon set (@iconify-json/solar), CC BY 4.0, by 480 Design.
 */
export interface SolarIcon { body: string; width: number; height: number }

export const SOLAR_ICONS = ${JSON.stringify(out, null, 1)} as const satisfies Record<string, SolarIcon>;

export type SolarIconName = keyof typeof SOLAR_ICONS;
`;
await Bun.write(new URL('../src/icons.generated.ts', import.meta.url), file);
console.log(`wrote ${Object.keys(out).length} icons`);
