/**
 * Generates Android resources from @reilai/brand, so the native host never
 * hard-codes a color or redraws an icon:
 *  - assets/theme.json            palette (light/dark)
 *  - drawable/ic_tab_*.xml        Solar tab icons as vector drawables
 *  - mipmap-*                     adaptive launcher icon (logo on the brand gradient)
 * Runs before every Gradle build (preBuild → generateAndroidResources).
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { LOGO_SHAPES, PALETTES, SOLAR_ICONS, type SolarIconName } from '@reilai/brand';
import sharp from 'sharp';

const res = new URL('../android/app/src/main/res/', import.meta.url).pathname;
const assets = new URL('../android/app/src/main/assets/', import.meta.url).pathname;
mkdirSync(assets, { recursive: true });

writeFileSync(join(assets, 'theme.json'), JSON.stringify(PALETTES, null, 2));

function vector(name: SolarIconName) {
  const icon = SOLAR_ICONS[name];
  const paths = [...icon.body.matchAll(/<path([^>]*)\/?>/g)].map((m) => {
    const attrs = m[1]!;
    const d = attrs.match(/\sd="([^"]+)"/)?.[1] ?? '';
    const evenOdd = /fill-rule="evenodd"/.test(attrs);
    const opacity = attrs.match(/opacity="([^"]+)"/)?.[1];
    return `    <path android:fillColor="#FF000000"${opacity ? ` android:fillAlpha="${opacity}"` : ''}${
      evenOdd ? ' android:fillType="evenOdd"' : ''
    } android:pathData="${d}" />`;
  });
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by scripts/android-resources.ts from Solar (${name}) -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp" android:height="24dp"
    android:viewportWidth="${icon.width}" android:viewportHeight="${icon.height}">
${paths.join('\n')}
</vector>
`;
}

mkdirSync(join(res, 'drawable'), { recursive: true });
for (const [file, icon] of [
  ['ic_tab_sessions', 'sessions'],
  ['ic_tab_new', 'add'],
  ['ic_tab_settings', 'settings'],
] as const) {
  writeFileSync(join(res, 'drawable', `${file}.xml`), vector(icon));
}

// adaptive launcher icon: 108dp canvas, logo inside the 66dp safe zone
const densities = { mdpi: 1, hdpi: 1.5, xhdpi: 2, xxhdpi: 3, xxxhdpi: 4 } as const;
const fg = (px: number) => {
  const scale = (px * 0.42) / 886;
  return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${px}" height="${px}">
<g transform="translate(${(px - 770 * scale) / 2} ${(px - 886 * scale) / 2}) scale(${scale})" fill="#fff" stroke="#fff" stroke-width="3" stroke-linejoin="round">${LOGO_SHAPES}</g></svg>`);
};
const legacy = new URL('../../../packages/brand/icon.svg', import.meta.url).pathname;
for (const [d, k] of Object.entries(densities)) {
  const dir = join(res, `mipmap-${d}`);
  mkdirSync(dir, { recursive: true });
  await sharp(fg(Math.round(108 * k))).png().toFile(join(dir, 'ic_launcher_foreground.png'));
  await sharp(legacy).resize(Math.round(48 * k)).png().toFile(join(dir, 'ic_launcher.png'));
}
mkdirSync(join(res, 'mipmap-anydpi-v26'), { recursive: true });
writeFileSync(
  join(res, 'mipmap-anydpi-v26', 'ic_launcher.xml'),
  `<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
    <monochrome android:drawable="@mipmap/ic_launcher_foreground" />
</adaptive-icon>
`,
);
writeFileSync(
  join(res, 'drawable', 'launcher_background.xml'),
  `<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <gradient android:angle="315" android:startColor="#7467C7" android:endColor="#4A3F94" />
</shape>
`,
);
for (const mode of ['light', 'dark'] as const) {
  const p = PALETTES[mode];
  const dir = join(res, mode === 'light' ? 'values' : 'values-night');
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    join(dir, 'colors.xml'),
    `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by scripts/android-resources.ts -->
<resources>
    <color name="reil_bg">${p.bg}</color>
    <color name="reil_surface">${p.surface}</color>
    <color name="reil_primary">${p.primary}</color>
    <color name="reil_text">${p.text}</color>
</resources>
`,
  );
}
console.log('android resources generated');
